package com.abctreinamentos;
// Generated 13/11/2018 17:26:59 by Hibernate Tools 4.3.1

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long cdcurso;
	private String nome;
	private Long valor;
	private String url;

	public Curso() {
	}

	public Curso(Long cdcurso, String nome, Long valor, String url) {
		this.cdcurso = cdcurso;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	public Long getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(Long cdcurso) {
		this.cdcurso = cdcurso;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Long getValor() {
		return this.valor;
	}

	public void setValor(Long valor) {
		this.valor = valor;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@Override
	public String toString() {
		return "Curso [cdcurso= " + cdcurso + " nome= " + nome  + " valor= " + valor + " url=" + url + " ]";
	}

}
