package com.abctreinamentos;
// Generated 13/11/2018 17:26:59 by Hibernate Tools 4.3.1

/**
 * PagamentoId generated by hbm2java
 */
public class PagamentoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long cpf;
	private Long cdcurso;

	public PagamentoId() {
	}

	public PagamentoId(Long cpf, Long cdcurso) {
		this.cpf = cpf;
		this.cdcurso = cdcurso;
	}

	public Long getCpf() {
		return this.cpf;
	}

	public void setCpf(Long cpf) {
		this.cpf = cpf;
	}

	public Long getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(Long cdcurso) {
		this.cdcurso = cdcurso;
	}

}
